// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {discord} from '../models';

export function AcceptFriend(arg1:string):Promise<void>;

export function AcceptMessageRequest(arg1:string):Promise<void>;

export function AddReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Autocomplete(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:Array<main.CommandOptionInput>,arg9:string):Promise<Array<main.AutocompleteChoiceDTO>>;

export function CancelQRLogin():Promise<void>;

export function DeclineMessageRequest(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string):Promise<main.MessageDTO>;

export function ExecuteCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:Array<main.CommandOptionInput>,arg9:Array<main.CommandAttachmentInput>):Promise<void>;

export function GetChannels(arg1:string):Promise<Array<main.ChannelDTO>>;

export function GetDMChannels():Promise<Array<main.ChannelDTO>>;

export function GetFavoriteGifs():Promise<Array<main.GifDTO>>;

export function GetFriends():Promise<Array<main.FriendDTO>>;

export function GetGuildFolders():Promise<Array<main.ServerFolderDTO>>;

export function GetGuilds():Promise<Array<main.GuildDTO>>;

export function GetMessageRequests():Promise<Array<main.ChannelDTO>>;

export function GetMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function GetMessagesBefore(arg1:string,arg2:string):Promise<Array<main.MessageDTO>>;

export function GetPinnedMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function GetRoles(arg1:string):Promise<Array<main.RoleDTO>>;

export function GetUserProfile(arg1:string):Promise<main.ProfileDTO>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function Login(arg1:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function OnAutocompleteResponse(arg1:string,arg2:Array<discord.AutocompleteChoice>):Promise<void>;

export function OnError(arg1:Error):Promise<void>;

export function OnMemberListUpdate(arg1:string,arg2:Array<discord.User>):Promise<void>;

export function OnMessageCreate(arg1:discord.Message):Promise<void>;

export function OnMessageDelete(arg1:string,arg2:string):Promise<void>;

export function OnMessageUpdate(arg1:discord.Message):Promise<void>;

export function OnPendingUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function OnPresenceUpdate(arg1:string,arg2:string):Promise<void>;

export function OnQRCode(arg1:string):Promise<void>;

export function OnRAError(arg1:Error):Promise<void>;

export function OnReactionAdd(arg1:string,arg2:string,arg3:string,arg4:discord.Emoji):Promise<void>;

export function OnReactionRemove(arg1:string,arg2:string,arg3:string,arg4:discord.Emoji):Promise<void>;

export function OnReady(arg1:discord.Ready):Promise<void>;

export function OnStatus(arg1:string):Promise<void>;

export function OnToken(arg1:string):Promise<void>;

export function OnTypingStart(arg1:string,arg2:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveFriend(arg1:string):Promise<void>;

export function RemoveReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestMembers(arg1:string,arg2:string):Promise<void>;

export function SearchCommands(arg1:string,arg2:string,arg3:string):Promise<Array<main.CommandDTO>>;

export function SearchGifs(arg1:string):Promise<Array<main.GifDTO>>;

export function SendFiles(arg1:string,arg2:string,arg3:string,arg4:Array<main.UploadFileInput>):Promise<main.MessageDTO>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.MessageDTO>;

export function StartQRLogin():Promise<void>;

export function SwitchAccount(arg1:string):Promise<main.LoginResult>;

export function VotePoll(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;
