// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriend(arg1) {
  return window['go']['main']['App']['AcceptFriend'](arg1);
}

export function AddReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddReaction'](arg1, arg2, arg3);
}

export function Autocomplete(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Autocomplete'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CancelQRLogin() {
  return window['go']['main']['App']['CancelQRLogin']();
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetChannels(arg1) {
  return window['go']['main']['App']['GetChannels'](arg1);
}

export function GetDMChannels() {
  return window['go']['main']['App']['GetDMChannels']();
}

export function GetFavoriteGifs() {
  return window['go']['main']['App']['GetFavoriteGifs']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetGuildFolders() {
  return window['go']['main']['App']['GetGuildFolders']();
}

export function GetGuilds() {
  return window['go']['main']['App']['GetGuilds']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesBefore(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesBefore'](arg1, arg2);
}

export function GetPinnedMessages(arg1) {
  return window['go']['main']['App']['GetPinnedMessages'](arg1);
}

export function GetRoles(arg1) {
  return window['go']['main']['App']['GetRoles'](arg1);
}

export function GetUserProfile(arg1) {
  return window['go']['main']['App']['GetUserProfile'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OnAutocompleteResponse(arg1, arg2) {
  return window['go']['main']['App']['OnAutocompleteResponse'](arg1, arg2);
}

export function OnError(arg1) {
  return window['go']['main']['App']['OnError'](arg1);
}

export function OnMemberListUpdate(arg1, arg2) {
  return window['go']['main']['App']['OnMemberListUpdate'](arg1, arg2);
}

export function OnMessageCreate(arg1) {
  return window['go']['main']['App']['OnMessageCreate'](arg1);
}

export function OnMessageDelete(arg1, arg2) {
  return window['go']['main']['App']['OnMessageDelete'](arg1, arg2);
}

export function OnMessageUpdate(arg1) {
  return window['go']['main']['App']['OnMessageUpdate'](arg1);
}

export function OnPendingUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OnPendingUser'](arg1, arg2, arg3, arg4);
}

export function OnPresenceUpdate(arg1, arg2) {
  return window['go']['main']['App']['OnPresenceUpdate'](arg1, arg2);
}

export function OnQRCode(arg1) {
  return window['go']['main']['App']['OnQRCode'](arg1);
}

export function OnRAError(arg1) {
  return window['go']['main']['App']['OnRAError'](arg1);
}

export function OnReactionAdd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OnReactionAdd'](arg1, arg2, arg3, arg4);
}

export function OnReactionRemove(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OnReactionRemove'](arg1, arg2, arg3, arg4);
}

export function OnReady(arg1) {
  return window['go']['main']['App']['OnReady'](arg1);
}

export function OnStatus(arg1) {
  return window['go']['main']['App']['OnStatus'](arg1);
}

export function OnToken(arg1) {
  return window['go']['main']['App']['OnToken'](arg1);
}

export function OnTypingStart(arg1, arg2) {
  return window['go']['main']['App']['OnTypingStart'](arg1, arg2);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RemoveFriend(arg1) {
  return window['go']['main']['App']['RemoveFriend'](arg1);
}

export function RemoveReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveReaction'](arg1, arg2, arg3);
}

export function RequestMembers(arg1, arg2) {
  return window['go']['main']['App']['RequestMembers'](arg1, arg2);
}

export function SearchCommands(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCommands'](arg1, arg2, arg3);
}

export function SearchGifs(arg1) {
  return window['go']['main']['App']['SearchGifs'](arg1);
}

export function SendFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFiles'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function StartQRLogin() {
  return window['go']['main']['App']['StartQRLogin']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function VotePoll(arg1, arg2, arg3) {
  return window['go']['main']['App']['VotePoll'](arg1, arg2, arg3);
}
